apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appvote.fullname" . }}-result
  labels:
    app: result
    {{- include "appvote.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.result.replicas }}
  selector:
    matchLabels:
      app: result
      {{- include "appvote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: result
        {{- include "appvote.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: result
        image: "{{ .Values.result.image.repository }}:{{ .Values.result.image.tag }}"
        imagePullPolicy: {{ .Values.result.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.result.service.targetPort }}
          protocol: TCP
