apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
    {{- include "appvote.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.vote.service.port }}
    targetPort: http
    protocol: TCP
    name: vote-service
  selector:
    app: vote
    {{- include "appvote.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    {{- include "appvote.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.vote.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: {{ .Values.vote.service.port }}
