apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
    {{- include "appvote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
  - port: {{ .Values.vote.service.port }}
    targetPort: http
    protocol: TCP
    name: vote-service
    {{- if and (eq .Values.vote.service.type "NodePort") .Values.vote.service.nodePort }}
    nodePort: {{ .Values.vote.service.nodePort }}
    {{- end }}
  selector:
    app: vote
    {{- include "appvote.selectorLabels" . | nindent 4 }}
